{
  "version": "2.0.0",
  "system": {
    "language": "es",
    "units": "mm",
    "theme": "light"
  },
  "calibration": null,
  "hardware": {
    "camera": {
      "device_id": 0,
      "resolution": [
        1920,
        1080
      ],
      "fps": 30
    },
    "gpio": {
      "enabled": false,
      "led_pin": 18,
      "button_pin": 19
    },
    "arduino": {
      "enabled": false,
      "port": "/dev/ttyUSB0",
      "baudrate": 9600
    }
  },
  "library": {
    "platens": [
      {
        "id": "default_platen",
        "name": "Plancha 40x50cm",
        "size_mm": [
          400,
          500
        ]
      }
    ],
    "styles": [
      {
        "id": "basic_tshirt",
        "name": "Camiseta Básica",
        "logos": [
          {
            "id": "chest",
            "name": "Pecho",
            "position_mm": {
              "x": 200,
              "y": 150
            },
            "tolerance_mm": 2.0,
            "detector_type": "contour",
            "roi": {
              "x": 150,
              "y": 100,
              "width": 100,
              "height": 100
            },
            "detector_params": {},
            "instructions": "Centrar logo en el pecho"
          },
          {
            "id": "sleeve",
            "name": "Manga",
            "position_mm": {
              "x": 350,
              "y": 200
            },
            "tolerance_mm": 1.5,
            "detector_type": "aruco",
            "roi": {
              "x": 300,
              "y": 150,
              "width": 100,
              "height": 100
            },
            "detector_params": {
              "aruco": {
                "expected_id": 42
              }
            },
            "instructions": "Alinear con costura de manga"
          }
        ]
      },
      {
        "id": "Comunicaciones Corinta__",
        "name": "Comunicaciones Corinta  ",
        "logos": [
          {
            "id": "logo_1",
            "name": "Logo transfer 2.png",
            "position_mm": {
              "x": 294.7970267534256,
              "y": 302.9074712693691
            },
            "tolerance_mm": 5.0,
            "detector_type": "template_matching",
            "roi": {
              "x": 142.27002675342558,
              "y": 125.23447126936912,
              "width": 305.05400000000003,
              "height": 355.346
            },
            "detector_params": {},
            "instructions": null
          }
        ]
      }
    ],
    "variants": [
      {
        "id": "tshirt_m",
        "style_id": "basic_tshirt",
        "size": "M",
        "scale_factor": 1.0,
        "offsets": {}
      },
      {
        "id": "tshirt_l",
        "style_id": "basic_tshirt",
        "size": "L",
        "scale_factor": 1.1,
        "offsets": {
          "chest": {
            "x": 0,
            "y": 10
          },
          "sleeve": {
            "x": 5,
            "y": 5
          }
        }
      }
    ]
  },
  "session": {
    "active_platen_id": "default_platen",
    "active_style_id": "basic_tshirt",
    "active_variant_id": "tshirt_m",
    "operator_id": null
  }
}