schema_version: 3
language: es
preset_path: presets/example_tshirt.json
calibration_path: /home/mauro/code/alignpress_pro_phase1/calibracion_nueva.json
dataset:
  path: /home/mauro/code/alignpress_pro_phase1/datasets/sample_images
  fps: 30.0
  loop: false
logging:
  output_dir: /home/mauro/code/alignpress_pro_phase1/logs
  formats:
  - csv
  - json
ui:
  theme: light
  operator_fullscreen: false
  kiosk_mode: false
  technical_pin: '2468'
  onboarding_completed: true
  camera_layout: single
assets:
  platens_dir: /home/mauro/code/alignpress_pro_phase1/platens
  styles_dir: /home/mauro/code/alignpress_pro_phase1/styles
  variants_dir: /home/mauro/code/alignpress_pro_phase1/variants
  job_cards_dir: /home/mauro/code/alignpress_pro_phase1/logs/job_cards
selection:
  platen_path: /home/mauro/code/alignpress_pro_phase1/platens/default_platen.json
  style_path: /home/mauro/code/alignpress_pro_phase1/styles/example_style.json
  variant_path: /home/mauro/code/alignpress_pro_phase1/variants/example_variant.json
calibration_reminder_days: 7
calibration_expire_days: 30
