{
  "version": "2.0.0",
  "system": {
    "language": "es",
    "units": "mm",
    "theme": "light"
  },
  "calibration": null,
  "hardware": {
    "camera": {
      "device_id": 0,
      "resolution": [
        1920,
        1080
      ],
      "fps": 30
    },
    "gpio": {
      "enabled": false,
      "led_pin": 18,
      "button_pin": 19
    },
    "arduino": {
      "enabled": false,
      "port": "/dev/ttyUSB0",
      "baudrate": 9600
    }
  },
  "library": {
    "platens": [],
    "styles": [
      {
        "id": "__",
        "name": "  ",
        "logos": [
          {
            "id": "logo_1",
            "name": "Logo comunicaciones.png",
            "position_mm": {
              "x": 394.94338512420654,
              "y": 174.19824308156967
            },
            "tolerance_mm": 5.0,
            "detector_type": "template_matching",
            "roi": {
              "x": 377.3119840025902,
              "y": 160.97324308156968,
              "width": 35.26280224323273,
              "height": 26.45
            },
            "detector_params": {},
            "instructions": null
          },
          {
            "id": "logo_2",
            "name": "Logo gulf.png",
            "position_mm": {
              "x": 154.45107382535934,
              "y": 217.2188618183136
            },
            "tolerance_mm": 5.0,
            "detector_type": "template_matching",
            "roi": {
              "x": 136.81967270374298,
              "y": 199.5888618183136,
              "width": 35.26280224323273,
              "height": 35.26
            },
            "detector_params": {},
            "instructions": null
          },
          {
            "id": "logo_3",
            "name": "Logo gana.png",
            "position_mm": {
              "x": 248.60275581479073,
              "y": 339.23
            },
            "tolerance_mm": 5.0,
            "detector_type": "template_matching",
            "roi": {
              "x": 230.97135469317436,
              "y": 321.6,
              "width": 35.26280224323273,
              "height": 35.26
            },
            "detector_params": {},
            "instructions": null
          }
        ]
      }
    ],
    "variants": []
  },
  "session": {
    "active_platen_id": null,
    "active_style_id": null,
    "active_variant_id": null,
    "operator_id": null
  }
}